/* ---------------------------------------------------------------------------
 * bp_offsets.h -- GENERATED by tools/gen_headers.py from the game binaries and
 * the Unity 2020.3.15f2 reference pair. Do not hand-edit; regenerate.
 *
 *   game libunity.so   BuildID e3e37b8a7a6d00dd10883c9d2cbb8f22afeee3e1
 *   game libil2cpp.so  BuildID 5e86ab0895b7e924f5197405d4756f87b125948d
 *   reference          libunity_sym.so + libunity2020315f2.so, BuildID 3e69862b...
 *
 * The game's libunity is NOT the stock prebuilt: it was relinked with engine
 * code stripping (different BuildID, 5 MB less .text, 18 of 29 Time bindings
 * absent). So nothing here was read straight off the reference. Each function
 * was named in the reference and located in the game by masked-instruction
 * fingerprint (ADRP/ADR/B/BL/LDR-literal immediates and ADRP-paired lo12
 * offsets wildcarded, everything else exact), or -- for the tiny icall
 * bindings that cannot be fingerprinted -- through the game's own icall
 * registration blocks, then body-checked against the named reference.
 *
 * Every RVA carries the game's own leading words as a guard. Consumers verify
 * before writing and SKIP on mismatch; see bp_patches.c / bp_icall.c.
 * MIT.
 * ------------------------------------------------------------------------- */
#ifndef BP_OFFSETS_H
#define BP_OFFSETS_H
#include <stdint.h>

typedef struct { const char *name; uint32_t rva; uint32_t size; uint32_t guard[4]; } BpSite;

/* ======================= VSYNC (pumped, NOT patched -- see bp_vsync.c) ===== */
#define BP_RVA_GetVSyncCounter        0x03bb4d8u  /* ref 0x069a320 GetVSyncCounter(), fp 1.000/0.583 */
static const uint32_t BP_GUARD_GetVSyncCounter[4] = { 0xf81e0ff4u, 0xa9017bf3u, 0xb0006eb3u, 0x9133b273u };
#define BP_RVA_WaitVSync              0x03bb510u  /* ref 0x069a358 WaitVSync(int), fp 1.000/0.190 */
static const uint32_t BP_GUARD_WaitVSync[4] = { 0xa9be53f5u, 0xa9017bf3u, 0x2a0003f3u, 0x97ff7b50u };
#define BP_RVA_GetVSyncTime           0x03bb574u  /* ref 0x069a3bc GetVSyncTime(int, bool), fp 0.985/0.000 */
static const uint32_t BP_GUARD_GetVSyncTime[4] = { 0xfc1c0fe8u, 0xf90007f8u, 0xa9015bf7u, 0xa90253f5u };
#define BP_RVA_GetFrameTimeNanos      0x03bb6a0u  /* ref 0x069a4e8 GetFrameTimeNanos(), fp 1.000/0.100 */
static const uint32_t BP_GUARD_GetFrameTimeNanos[4] = { 0xa9bf7bf3u, 0xb0006ea0u, 0x91330000u, 0x940d693fu };
/* WaitVSync(target): lock mutex; while (counter < target) cond_wait; unlock.
 * Same mutex@+0 / cond@+0x28 / counter@+0x58 block shape as Unity 6 (but the
 * counter is a 32-bit int here). All three in .bss, zero-initialised, which is
 * a valid bionic mutex/cond. Read out of WaitVSync's own adrp/add+ldr pairs. */
#define BP_VSYNC_MUTEX    0x1190cecu
#define BP_VSYNC_COND     0x1190d14u
#define BP_VSYNC_COUNTER  0x1190d44u   /* int32 */
/* WaitVSync body words carrying the block address (verified at runtime): */
static const uint32_t BP_GUARD_WaitVSync_state[4] = { 0xb0006eb4u, 0x9133b294u, 0xaa1403e0u, 0x97f3c409u };  /* +0x20..+0x2c */

/* ======================= SWAPPY (statically linked in 2020.3) ============ */
/* androidUseSwappy=False in this game's PlayerSettings, so these should be
 * inert on their own. Belt and braces: Swappy must never start, because its
 * Java choreographer thread would wait for callbacks that cannot arrive. */
#define BP_RVA_Swappy_IsEnabledAndActive          0x039a25cu  /* PATCH ret 0; fp 1.000/0.500 */
static const uint32_t BP_GUARD_Swappy_IsEnabledAndActive[4] = { 0xf81f0ffeu, 0x940d5ffeu, 0xb4000120u, 0x394fd808u };
#define BP_RVA_SwappyGL_Init                      0x039a46cu  /* PATCH ret; fp 1.000/0.275 */
static const uint32_t BP_GUARD_SwappyGL_Init[4] = { 0xd100c3ffu, 0xf9000bf4u, 0xa9027bf3u, 0x940d5f78u };
#define BP_RVA_Swappy_CheckDeviceSupport          0x039a548u  /* PATCH ret 0; fp 0.977/0.116 */
static const uint32_t BP_GUARD_Swappy_CheckDeviceSupport[4] = { 0xf81d0ff6u, 0xa90153f5u, 0xa9027bf3u, 0xb0006f96u };
#define BP_RVA_Swappy_UpdateSwapInterval          0x039a2c0u  /* PATCH ret; fp 1.000/0.100 */
static const uint32_t BP_GUARD_Swappy_UpdateSwapInterval[4] = { 0xd10143ffu, 0xa9047bf3u, 0x910003e8u, 0x94003d4au };
#define BP_RVA_Swappy_UpdateFrameInterval         0x039a290u  /* PATCH ret; fp 1.000/0.273 */
static const uint32_t BP_GUARD_Swappy_UpdateFrameInterval[4] = { 0xf81f0ffeu, 0xd0006bc8u, 0xb908ed00u, 0x97f8e86eu };
#define BP_RVA_SwappyGL_Swap                      0x039a40cu  /* record only; fp 1.000/0.652 */
static const uint32_t BP_GUARD_SwappyGL_Swap[4] = { 0xf81e0ff4u, 0xa9017bf3u, 0xaa0103f3u, 0xaa0003f4u };
#define BP_RVA_Swappy_GetRequiredSwapIntervalNS   0x039a368u  /* record only; fp 1.000/0.000 */
static const uint32_t BP_GUARD_Swappy_GetRequiredSwapIntervalNS[4] = { 0xa9bf7bf3u, 0xaa0003f3u, 0x940d5fbau, 0xb4000480u };

/* ======================= ENGINE PATCHES ================================== */
#define BP_RVA_APK_CanHandle                0x03adc84u  /* ret 0: no APK here; stops the zip scan per open; fp 1.000/0.600 */
static const uint32_t BP_GUARD_APK_CanHandle[4] = { 0xd10143ffu, 0xf9001bf4u, 0xa9047bf3u, 0xd53bd054u };
#define BP_RVA_GetAndroidAudioOutputType    0x03b15f8u  /* ret 2 = OpenSL (1 = AudioTrack/Java); fp 1.000/0.091 */
static const uint32_t BP_GUARD_GetAndroidAudioOutputType[4] = { 0xa9be53f5u, 0xa9017bf3u, 0x2a0003f3u, 0x97ffffb8u };
#define BP_RVA_ApiLevel                     0x039e69cu  /* ret 33, matching jni_fake SDK_INT; fp 1.000/0.579 */
static const uint32_t BP_GUARD_ApiLevel[4] = { 0xf81e0ff4u, 0xa9017bf3u, 0xf0006f74u, 0xb942e693u };
#define BP_RVA_DVM_GetInternetReachability  0x03a2184u  /* redirect -> bp_net_reachability(); fp 1.000/0.105 */
static const uint32_t BP_GUARD_DVM_GetInternetReachability[4] = { 0xd10083ffu, 0xa9017bf3u, 0x910003e0u, 0x910003f3u };
#define BP_RVA_AttachSurface                0x03a9d48u  /* diagnostic only; fp 1.000/0.231 */
static const uint32_t BP_GUARD_AttachSurface[4] = { 0xf81e0ff4u, 0xa9017bf3u, 0x37f801c0u, 0x2a0003f3u };
#define BP_RVA_GetTimeManager               0x01d16c4u  /* called by the Time hooks for pass-through fields; fp 1.000/0.800 */
static const uint32_t BP_GUARD_GetTimeManager[4] = { 0xf81f0ffeu, 0x32000be0u, 0x940084a9u, 0xf84107feu };
#define BP_RVA_AudioManager_InitNormal      0x05abb90u  /* diagnostic only; fp 1.000/0.000 */
static const uint32_t BP_GUARD_AudioManager_InitNormal[4] = { 0xd10543ffu, 0xa91163fcu, 0xa9125bf7u, 0xa91353f5u };
#define BP_RVA_FMOD_OutputOpenSL_init       0x0a66fc8u  /* diagnostic only; fp 0.996/0.000 */
static const uint32_t BP_GUARD_FMOD_OutputOpenSL_init[4] = { 0xd10303ffu, 0xa9085ff8u, 0xa90957f6u, 0xa90a4ff4u };

/* ======================= UNITYTLS CA STORE (bp_net.c) ==================== */
#define BP_RVA_unitytls_errorstate_create       0x0674060u  /* fp 1.000/0.500 n=4 */
static const uint32_t BP_GUARD_unitytls_errorstate_create[4] = { 0x529f58e0u, 0x72a0d960u, 0xaa1f03e1u, 0xd65f03c0u };
#define BP_RVA_unitytls_default_ca_enter_sync   0x067413cu  /* fp 1.000/0.227 n=25 */
static const uint32_t BP_GUARD_unitytls_default_ca_enter_sync[4] = { 0xa9bf7bf3u, 0xb4000240u, 0xb9400408u, 0xaa0003f3u };
#define BP_RVA_unitytls_default_ca_exit_sync    0x0674200u  /* fp 1.000/0.455 n=13 */
static const uint32_t BP_GUARD_unitytls_default_ca_exit_sync[4] = { 0xb4000141u, 0xb9400428u, 0x35000108u, 0xb9400028u };
#define BP_RVA_unitytls_x509list_append_pem     0x0676264u  /* fp 1.000/0.000 n=151 */
static const uint32_t BP_GUARD_unitytls_x509list_append_pem[4] = { 0xa9ba6ffcu, 0xa90167fau, 0xa9025ff8u, 0xa90357f6u };
/* The DER append Unity itself uses to fill this list from Android's trust store
 * (unitytls_x509verify_default_ca -> getAcceptedIssuers -> getEncoded), and the
 * list accessor used to count what actually landed. fp 1.000/0.297, 1.000/0.083. */
#define BP_RVA_unitytls_x509list_append_der  0x06749fcu
static const uint32_t BP_GUARD_unitytls_x509list_append_der[4] = { 0xa9bf7bf3u, 0xaa0303f3u, 0xb5000080u, 0xb4000073u };
#define BP_RVA_unitytls_x509list_get_x509    0x0674b00u
static const uint32_t BP_GUARD_unitytls_x509list_get_x509[4] = { 0xf100041fu, 0x54000101u, 0xb4000402u, 0xb9400448u };
/* Verification path (2020.3 reference): a TLS context's DEFAULT verify callback
 * tail-calls unitytls_x509verify_default_ca(chain, cn, cn_len, cb, ud, err),
 * which ends explicit_ca(chain, default_ca_get(err), cn, cn_len, cb, ud, err).
 * bp_net.c replaces default_ca with exactly those two calls plus diagnostics.
 * fp 1.000/0.157, 1.000/0.000, 1.000/0.087, 1.000/0.216. */
#define BP_RVA_unitytls_x509verify_default_ca     0x06768f4u
static const uint32_t BP_GUARD_unitytls_x509verify_default_ca[4]  = { 0xd10303ffu, 0xa9066ffcu, 0xa90767fau, 0xa9085ff8u };
#define BP_RVA_unitytls_x509verify_explicit_ca    0x0674b90u
static const uint32_t BP_GUARD_unitytls_x509verify_explicit_ca[4] = { 0xa9ba6ffcu, 0xa90167fau, 0xa9025ff8u, 0xa90357f6u };
#define BP_RVA_unitytls_x509verify_default_ca_get 0x0674090u
static const uint32_t BP_GUARD_unitytls_x509verify_default_ca_get[4] = { 0xd0005989u, 0xf942192au, 0xb400024au, 0xf9421929u };
#define BP_RVA_unitytls_x509_export_der           0x0674894u
static const uint32_t BP_GUARD_unitytls_x509_export_der[4]        = { 0xa9bf7bf3u, 0xf100041fu, 0x54000121u, 0xb4000303u };

/* ======================= TIME icall bindings (all 11 this build registers) ======================= */
static const BpSite BP_TIME_SITES[] = {
  { "get_deltaTime", 0x0400790u,  20u, { 0xf81f0ffeu, 0x97f743ccu, 0xbd40a800u, 0xf84107feu } },
  { "get_fixedDeltaTime", 0x04007d0u,  20u, { 0xf81f0ffeu, 0x97f743bcu, 0xbd404800u, 0xf84107feu } },
  { "get_frameCount", 0x040082cu,  20u, { 0xf81f0ffeu, 0x97f743a5u, 0xb940c800u, 0xf84107feu } },
  { "get_realtimeSinceStartup", 0x0400840u,  24u, { 0xf81f0ffeu, 0x97f743a0u, 0x97f74350u, 0x1e624000u } },
  { "get_smoothDeltaTime", 0x04007e4u,  20u, { 0xf81f0ffeu, 0x97f743b7u, 0xbd40b000u, 0xf84107feu } },
  { "get_time", 0x0400758u,  24u, { 0xf81f0ffeu, 0x97f743dau, 0xfd404800u, 0x1e624000u } },
  { "get_timeScale", 0x04007f8u,  20u, { 0xf81f0ffeu, 0x97f743b2u, 0xbd40fc00u, 0xf84107feu } },
  { "get_timeSinceLevelLoad", 0x0400770u,  32u, { 0xf81f0ffeu, 0x97f743d4u, 0xfd404800u, 0xfd407801u } },
  { "get_unscaledDeltaTime", 0x04007bcu,  20u, { 0xf81f0ffeu, 0x97f743c1u, 0xbd40ac00u, 0xf84107feu } },
  { "get_unscaledTime", 0x04007a4u,  24u, { 0xf81f0ffeu, 0x97f743c7u, 0xfd405000u, 0x1e624000u } },
  { "set_timeScale", 0x040080cu,  32u, { 0xfc1f0fe8u, 0xf90007feu, 0x4ea01c08u, 0x97f743abu } },
};

/* ======================= INPUT icall bindings ======================= */
static const BpSite BP_INPUT_SITES[] = {
  { "GetAxisRaw", 0x01b3b20u, 184u, { 0xd10203ffu, 0xfd002be8u, 0xf9002ff6u, 0xa90653f5u } },
  { "GetButtonDown", 0x01b3c50u, 176u, { 0xd10203ffu, 0xa9055bf7u, 0xa90653f5u, 0xa9077bf3u } },
  { "GetKeyDownInt", 0x01b3a28u,  64u, { 0xd10083ffu, 0xa900fbffu, 0x910003e1u, 0xf90003ffu } },
  { "GetKeyInt", 0x01b382cu,  64u, { 0xd10083ffu, 0xa900fbffu, 0x910003e1u, 0xf90003ffu } },
  { "GetKeyUpInt", 0x01b3930u,  64u, { 0xd10083ffu, 0xa900fbffu, 0x910003e1u, 0xf90003ffu } },
  { "GetMouseButton", 0x01b3d78u,  64u, { 0xd10083ffu, 0xa900fbffu, 0x910003e1u, 0xf90003ffu } },
  { "GetMouseButtonDown", 0x01b3e70u,  64u, { 0xd10083ffu, 0xa900fbffu, 0x910003e1u, 0xf90003ffu } },
  { "GetMouseButtonUp", 0x01b3f5cu,  64u, { 0xd10083ffu, 0xa900fbffu, 0x910003e1u, 0xf90003ffu } },
  { "GetTouch_Injected", 0x01b4048u,  80u, { 0xd101c3ffu, 0xa9067bf3u, 0xaa0103f3u, 0x910023e8u } },
  { "get_compositionCursorPos_Injected", 0x01b4368u,  28u, { 0xa9bf7bf3u, 0xaa0003f3u, 0x94008039u, 0xf9409c08u } },
  { "get_compositionString", 0x01b42dcu, 140u, { 0xd10143ffu, 0xf9001bf4u, 0xa9047bf3u, 0xd53bd054u } },
  { "get_imeCompositionMode", 0x01b42b0u,  20u, { 0xf81f0ffeu, 0x94008068u, 0xb9414400u, 0xf84107feu } },
  { "get_mousePosition_Injected", 0x01b4114u,  80u, { 0xd100c3ffu, 0xa9027bf3u, 0xaa0003f3u, 0x910003e8u } },
  { "get_mousePresent", 0x01b43a0u,  20u, { 0xf81f0ffeu, 0x9407b90du, 0x12000000u, 0xf84107feu } },
  { "get_mouseScrollDelta_Injected", 0x01b41f0u,  68u, { 0xd100c3ffu, 0xa9027bf3u, 0xaa0003f3u, 0x910023e8u } },
  { "get_touchCount", 0x01b43b4u,  16u, { 0xf81f0ffeu, 0x9407bdaeu, 0xf84107feu, 0xd65f03c0u } },
  { "get_touchSupported", 0x01b43c4u,  20u, { 0xf81f0ffeu, 0x94008799u, 0x12000000u, 0xf84107feu } },
  { "set_compositionCursorPos_Injected", 0x01b4384u,  28u, { 0xa9bf7bf3u, 0xaa0003f3u, 0x94008032u, 0xf9400268u } },
  { "set_imeCompositionMode", 0x01b42c4u,  24u, { 0xa9bf7bf3u, 0x2a0003f3u, 0x94008062u, 0xb9014413u } },
  { "set_multiTouchEnabled", 0x01b43d8u,  12u, { 0x72001c1fu, 0x1a9f07e0u, 0x1407be0au, 0xd0005ec0u } },  /* NOT hookable: 12 bytes < 16-byte stub */
};

/* ======================= SCREEN icall bindings ======================= */
static const BpSite BP_SCREEN_SITES[] = {
  { "GetScreenOrientation", 0x03d6078u,  24u, { 0xf81f0ffeu, 0x97f94f4bu, 0xf9400008u, 0xf9408901u } },
  { "get_currentResolution_Injected", 0x03d60c8u,  40u, { 0xa9bf7bf3u, 0xaa0003f3u, 0x97f94f36u, 0xf9400008u } },
  { "get_dpi", 0x03d6060u,  24u, { 0xf81f0ffeu, 0x97f94f51u, 0xf9400008u, 0xf9406d01u } },
  { "get_fullScreenMode", 0x03d60f0u,  24u, { 0xf81f0ffeu, 0x97f94f2du, 0xf9400008u, 0xf9407501u } },
  { "get_height", 0x03d6048u,  24u, { 0xf81f0ffeu, 0x97f94f57u, 0xf9400008u, 0xf9405d01u } },
  { "get_safeArea_Injected", 0x03d6108u,  40u, { 0xa9bf7bf3u, 0xaa0003f3u, 0x97f94f26u, 0xf9400008u } },
  { "get_sleepTimeout", 0x03d6090u,  24u, { 0xf81f0ffeu, 0x97f94f45u, 0xf9400008u, 0xf9404901u } },
  { "get_width", 0x03d6030u,  24u, { 0xf81f0ffeu, 0x97f94f5du, 0xf9400008u, 0xf9405901u } },
  { "set_sleepTimeout", 0x03d60a8u,  32u, { 0xa9bf7bf3u, 0x2a0003f3u, 0x97f94f3eu, 0xf9400008u } },
};
#define BP_NSITES(a) ((int)(sizeof(a) / sizeof((a)[0])))

/* ======================= BOEHM GC STOP-THE-WORLD BRIDGE (libil2cpp) ====== */
/* Derived from the only two pthread_kill and two sem_post call sites in this
 * libil2cpp (tools/derive_gc_bridge.py). Three contiguous ints in .data, the ack
 * semaphore in .bss, all inside the last RW PT_LOAD -- the layout every port in
 * this lineage shows. Offsets are virtual addresses within the mapped module. */
#define GC_START_ACK_OFF   0x25bbd30u  /* GC_retry_signals, restart-ack gate */
#define GC_SUSPEND_SIG_OFF 0x25bbd34u  /* GC_sig_suspend      (int)          */
#define GC_RESTART_SIG_OFF 0x25bbd38u  /* GC_sig_thr_restart  (int)          */
#define GC_ACK_SEM_OFF     0x25cc060u  /* GC_suspend_ack_sem  (sem_t / void*) */
typedef struct { uint32_t off; uint32_t word; const char *what; } GcGuard;
#define BP_GC_GUARDS_INIT { \
  { 0x07de310u, 0xb000eee8u, "GC_sig_suspend: adrp x8, #0x25bb000" }, \
  { 0x07de33cu, 0xb000eee8u, "GC_sig_suspend: adrp x8, #0x25bb000" }, \
  { 0x07de340u, 0xb94d3501u, "GC_sig_suspend: ldr w1, [x8, #0xd34]" }, \
  { 0x07de350u, 0xb94d3901u, "GC_sig_thr_restart: ldr w1, [x8, #0xd38]" }, \
  { 0x07de3d4u, 0xb000eee8u, "gate: adrp x8, #0x25bb000" }, \
  { 0x07de458u, 0xb000eee8u, "gate: adrp x8, #0x25bb000" }, \
  { 0x07de45cu, 0xb94d3108u, "gate: ldr w8, [x8, #0xd30]" }, \
  { 0x07de490u, 0xd000ef60u, "ack_sem: adrp x0, #0x25cc000" }, \
  { 0x07de494u, 0x91018000u, "ack_sem: add x0, x0, #0x60" }, \
  { 0x07de4e4u, 0xd000ef60u, "ack_sem: adrp x0, #0x25cc000" }, \
  { 0x07de4e8u, 0x91018000u, "ack_sem: add x0, x0, #0x60" }, \
}
/* file-time values: gate=1 suspend=-1 restart=-1 (bdwgc SIGNAL_UNSET is -1; GC_stop_init stores 30/24) */

/* ======================= ENGINE CLOCK (badpiggies_nx approach, 2020.3) ===== */
/* TimeManager::Update(double): detoured so the engine clock advances on a
 * monotonic wall clock (bp_tmclock.c). 2020.3.15f2's prologue builds a 0x20
 * frame saving d8/x20/x19/x30 -- NOT 2020.3.39f1's 0x30 frame with d9 -- and
 * the body at +0x3c exits through the shared epilogue at +0x2c, so
 * bp_tm_trampoline.s replicates exactly this prologue. The 15-word guard covers
 * the whole prologue, which pins all three field offsets. fp 1.000/0.000 */
#define BP_RVA_TimeManager_Update     0x01d10c0u
#define BP_TM_BODY_OFF                0x3cu
#define BP_TM_BODY_WORD               0x4ea01c08u   /* mov v8.16b, v0.16b */
static const uint32_t BP_GUARD_TimeManager_Update[15] = { 0xfc1e0fe8u, 0xf90007f4u, 0xa9017bf3u, 0xf9406408u, 0xb940d009u, 0x3943e00au, 0x91000508u, 0x11000529u, 0xf9006408u, 0xb900d009u, 0x340000aau, 0xa9417bf3u, 0xf94007f4u, 0xfc4207e8u, 0xd65f03c0u };
#define BP_TM_FIELD_FRAMECOUNT        0xc8
#define BP_TM_FIELD_AUX               0xd0
#define BP_TM_FIELD_PAUSE             0xf8
#define BP_RVA_TimeManager_SetTimeScale 0x01d149cu  /* fp 1.000/0.057 */
static const uint32_t BP_GUARD_TimeManager_SetTimeScale[4] = { 0xd10283ffu, 0xf90043f4u, 0xa9097bf3u, 0xd53bd053u };
#define BP_RVA_GetTimeSinceStartup    0x02a02e0u  /* diagnostic; fp 1.000/0.615 */

/* EnableFrameTimeTracker(): lazily constructs s_FrameTimeTracker, whose ctor
 * starts an Android Looper over JNI and waits on a Monitor for a thread that is
 * never spawned here -- badpiggies_nx's "frame-2 hang". Patched to `ret`.
 * Confirmed three ways for this build: fingerprint (fp 1.000/0.667),
 * its only caller sits inside UnityPause, and it loads s_FrameTimeTracker from
 * 0x1190d80 -- exactly where the vsync-block delta predicts. */
#define BP_RVA_EnableFrameTimeTracker 0x03bb714u
static const uint32_t BP_GUARD_EnableFrameTimeTracker[4] = { 0xd10083ffu, 0xa9017bf3u, 0x910023e0u, 0x910023f3u };

/* FMOD::OutputOpenSL::init (fp 0.996/0.000). 2020.3's FMOD OpenSL output is
 * instruction-identical to the code bouncemasters_nx patched: same 0x3f8
 * framesPerBuffer field, same four guard words, bound check at the same +0x180.
 *   PERIOD   ldr w9,[x19,#0x3f8] ; cbz w9  -> movz w9,#PERIOD ; str w9,[x19,#0x3f8]
 *   BUFGEOM  b.ls (after the halving)    -> b      (always the success path)
 *   BUFCOUNT udiv w9,w10,w9               -> movz w9,#UPFRONT  (N can never be 0) */
#define BP_RVA_FMOD_PERIOD_LDR      0x0a67124u  /* +0x15c: ldr w9, [x19, #0x3f8] */
#define BP_GUARD_FMOD_PERIOD_LDR    0xb943fa69u
#define BP_RVA_FMOD_PERIOD_CBZ      0x0a67128u  /* +0x160: cbz w9, #0xa6714c */
#define BP_GUARD_FMOD_PERIOD_CBZ    0x34000129u
#define BP_RVA_FMOD_BUFGEOM_BRANCH  0x0a67148u  /* +0x180: b.ls #0xa67158 */
#define BP_GUARD_FMOD_BUFGEOM_BRANCH 0x54000089u
#define BP_RVA_FMOD_BUFCOUNT        0x0a671a4u  /* +0x1dc: udiv w9, w10, w9 */
#define BP_GUARD_FMOD_BUFCOUNT      0x1ac90949u


/* ======================= BDWGC THREAD TABLE (tools/offsets/derive_gc_threads.py) ==
 * What Boehm's suspend SIGNAL HANDLER writes on Linux: each stopped thread's
 * stop_info.stack_ptr (where GC_push_all_stacks starts scanning; it aborts if
 * NULL) and last_stop_count. No signal ever runs here, so libc_shim.c's bridge
 * writes them itself, plus the thread's registers below its SP, from the
 * context of the really-paused thread. Every value is pinned by the guard
 * words of the collector instructions that use it. */
#define GC_THREADS_OFF        0x25c9600u  /* GC_threads[] */
#define GC_THREADS_BUCKETS    256
#define GC_THR_NEXT_OFF       0x0
#define GC_THR_ID_OFF         0x8
#define GC_THR_LASTSTOP_OFF   0x10   /* stop_info.last_stop_count */
#define GC_THR_STACKPTR_OFF   0x18   /* stop_info.stack_ptr */
#define GC_STOP_COUNT_OFF     0x25c95e0u  /* GC_stop_count */
#define BP_GC_THREAD_GUARDS_INIT { \
  { 0x07de570u, 0x911802d6u, "GC_threads base (add)" }, \
  { 0x07de580u, 0xf8757adau, "bucket load" }, \
  { 0x07de588u, 0xf9400740u, "p->id (pthread_kill arg)" }, \
  { 0x07de5a4u, 0xf9400b48u, "p->stop_info.last_stop_count" }, \
  { 0x07de5a8u, 0xf942f2e9u, "GC_stop_count" }, \
  { 0x07de5e4u, 0xf940035au, "p->next" }, \
  { 0x07de5f0u, 0xf10402bfu, "bucket count" }, \
  { 0x07dd838u, 0xf9400f95u, "GC_push_all_stacks: lo = p->stop_info.stack_ptr" }, \
  { 0x07dd85cu, 0xb40005d5u, "cbz lo -> abort(sp not set)" }, \
}

#endif /* BP_OFFSETS_H */
