/* ---------------------------------------------------------------------------
 * bp_patch_granularity.h -- GENERATED by tools/gen_headers.py. Do not hand-edit.
 *
 * Moves Unity 2020.3.15f2's block allocator from 256 MB regions to 64 MB, for
 * Bloons Pop's libunity.so (BuildID e3e37b8a7a6d00dd10883c9d2cbb8f22afeee3e1).
 *
 * DERIVATION. Two independent passes that agree site-for-site:
 *   1. blind: every 256 MB-class encoding in the allocator neighbourhood of the
 *      game binary, attributed to functions via .eh_frame FDE ranges;
 *   2. named: every 256 MB-class encoding in the 2020.3.15f2 REFERENCE build,
 *      attributed by symbol (libunity_sym.so), each owning function mapped onto
 *      the game by masked-instruction fingerprint (all ten at score 1.000), and
 *      each site word checked identical in the game.
 * Both produce the same 21 words in the same 10 functions.
 *
 * THREE WAYS 2020.3 DIFFERS FROM THE 2021+/Unity 6 TABLES (and from the
 * inherited scan_granularity.py, which would have got all three wrong):
 *   - level 1 of the region index is `lsr #28 ; asr #12` (== ptr>>40), not
 *     `lsr #40`, so rewriting the lsr #28 moves BOTH levels -- there are no
 *     separate [L1] sites;
 *   - six sites encode 256 MB as ORR bitmask immediates (mov w8,#0x10000000 /
 *     mov w9,#0xfffffff), which the inherited scanner does not recognise;
 *   - GetMemoryBlockFromPointer builds its 255-region walk-back constant with
 *     orr+movk. Rewriting only the movk (the inherited transform) yields
 *     -1023 regions instead of -255, so BOTH words are rewritten here.
 *
 * VERIFY-FIRST, ALL-OR-NOTHING (see bp_patches.c). MUST equal MMAP_ARENA_ALIGN.
 * MIT.
 * ------------------------------------------------------------------------- */
#ifndef BP_PATCH_GRANULARITY_H
#define BP_PATCH_GRANULARITY_H
#include <stdint.h>
typedef struct { uint32_t rva; uint32_t from; uint32_t to; const char *what; } BpPatchWord;
#define BP_REGION_GRANULARITY_MB 64u
static const BpPatchWord BP_GRANULARITY_WORDS[] = {
  /*  0 */ { 0x01ea1b4u, 0x32006fe9u, 0x320067e9u, "LocalLowLevelAllocator::ReserveMemoryBlock +0x9c" },  /* mov w9, #0xfffffff -> mov w9, #0x3ffffff */
  /*  1 */ { 0x01ea1bcu, 0x92648d36u, 0x92669536u, "LocalLowLevelAllocator::ReserveMemoryBlock +0xa4" },  /* and x22, x9, #0xfffffffff0000000 -> and x22, x9, #0xfffffffffc000000 */
  /*  2 */ { 0x01eaea8u, 0xd35cfc33u, 0xd35afc33u, "MemoryManager::VirtualAllocator::MarkMemoryBlocks +0x10" },  /* lsr x19, x1, #0x1c -> lsr x19, x1, #0x1a */
  /*  3 */ { 0x01eaeacu, 0xd35cfd15u, 0xd35afd15u, "MemoryManager::VirtualAllocator::MarkMemoryBlocks +0x14" },  /* lsr x21, x8, #0x1c -> lsr x21, x8, #0x1a */
  /*  4 */ { 0x01eaf24u, 0x320403e8u, 0x320603e8u, "MemoryManager::VirtualAllocator::ReserveMemoryBlock +0x24" },  /* mov w8, #0x10000000 -> mov w8, #0x4000000 */
  /*  5 */ { 0x01eb11cu, 0xd35cfc2cu, 0xd35afc2cu, "MemoryManager::VirtualAllocator::GetMemoryBlockFromPointer +0x0" },  /* lsr x12, x1, #0x1c -> lsr x12, x1, #0x1a */
  /*  6 */ { 0x01eb12cu, 0x92648c28u, 0x92669428u, "MemoryManager::VirtualAllocator::GetMemoryBlockFromPointer +0x10" },  /* and x8, x1, #0xfffffffff0000000 -> and x8, x1, #0xfffffffffc000000 */
  /*  7 */ { 0x01eb134u, 0xd35c9c2au, 0xd35a942au, "MemoryManager::VirtualAllocator::GetMemoryBlockFromPointer +0x18" },  /* ubfx x10, x1, #0x1c, #0xc -> ubfx x10, x1, #0x1a, #0xc */
  /*  8 */ { 0x01eb148u, 0xb25c6febu, 0xb25e77ebu, "MemoryManager::VirtualAllocator::GetMemoryBlockFromPointer +0x2c" },  /* mov x11, #-0x1000000000 -> mov x11, #-0x400000000 */
  /*  9 */ { 0x01eb14cu, 0xf2a2000bu, 0xf2a0800bu, "MemoryManager::VirtualAllocator::GetMemoryBlockFromPointer +0x30" },  /* movk x11, #0x1000, lsl #16 -> movk x11, #0x400, lsl #16 */
  /* 10 */ { 0x01eb188u, 0xcb0a7108u, 0xcb0a6908u, "MemoryManager::VirtualAllocator::GetMemoryBlockFromPointer +0x6c" },  /* sub x8, x8, x10, lsl #28 -> sub x8, x8, x10, lsl #26 */
  /* 11 */ { 0x01eb1a0u, 0xd35cfc28u, 0xd35afc28u, "MemoryManager::VirtualAllocator::GetBlockInfoFromPointer +0x0" },  /* lsr x8, x1, #0x1c -> lsr x8, x1, #0x1a */
  /* 12 */ { 0x01eb1b4u, 0xd35c9c29u, 0xd35a9429u, "MemoryManager::VirtualAllocator::GetBlockInfoFromPointer +0x14" },  /* ubfx x9, x1, #0x1c, #0xc -> ubfx x9, x1, #0x1a, #0xc */
  /* 13 */ { 0x01ec824u, 0xd35cfc28u, 0xd35afc28u, "MemoryManager::GetAllocatorContainingPtr +0xc" },  /* lsr x8, x1, #0x1c -> lsr x8, x1, #0x1a */
  /* 14 */ { 0x01ec840u, 0xd35c9e89u, 0xd35a9689u, "MemoryManager::GetAllocatorContainingPtr +0x28" },  /* ubfx x9, x20, #0x1c, #0xc -> ubfx x9, x20, #0x1a, #0xc */
  /* 15 */ { 0x01ecca0u, 0x320403e0u, 0x320603e0u, "AtomicPageAllocator::AllocatePage +0x48" },  /* mov w0, #0x10000000 -> mov w0, #0x4000000 */
  /* 16 */ { 0x01ed310u, 0x32006feau, 0x320067eau, "BucketAllocator::BucketAllocator +0x84" },  /* mov w10, #0xfffffff -> mov w10, #0x3ffffff */
  /* 17 */ { 0x01ed320u, 0x92648d01u, 0x92669501u, "BucketAllocator::BucketAllocator +0x94" },  /* and x1, x8, #0xfffffffff0000000 -> and x1, x8, #0xfffffffffc000000 */
  /* 18 */ { 0x01ef254u, 0x320403e9u, 0x320603e9u, "DynamicHeapAllocator::DynamicHeapAllocator +0x54" },  /* mov w9, #0x10000000 -> mov w9, #0x4000000 */
  /* 19 */ { 0x01ef6c4u, 0x32006feau, 0x320067eau, "DynamicHeapAllocator::RequestLargeAllocMemory +0x90" },  /* mov w10, #0xfffffff -> mov w10, #0x3ffffff */
  /* 20 */ { 0x01ef6ccu, 0x92648d36u, 0x92669536u, "DynamicHeapAllocator::RequestLargeAllocMemory +0x98" },  /* and x22, x9, #0xfffffffff0000000 -> and x22, x9, #0xfffffffffc000000 */
};
#define BP_GRANULARITY_WORDS_N ((int)(sizeof(BP_GRANULARITY_WORDS) / sizeof(BP_GRANULARITY_WORDS[0])))
#endif
